title: Jeremy Stigter
description: >-
  Jeremy Stigter, photographer, Paris. Currently: Eyes Wide Open / Les Yeux
  Ouverts, three episodes in the history of the Front National.
baseurl: ""
url: "https://jeremystigter.com"
exclude:
  - README.md
